### ISSUE TITLE
Support any CSS color value for NFT metadata

### ISSUE THREAD

**Issue by vikiival** [rmrk-team/rmrk-spec#25]
```json
  "background_color": {
    "type": "string",
    "description": "Background color of the item. Must be a six-character hexadecimal without #."
  },
```

Kanaria is using HEX format with `#` prefix

The goal of this issue is to support any [CSS Color Value (except current color)](https://www.w3schools.com/colors/default.asp)

```
With CSS, colors can be specified in different ways:

By color names
As RGB values
As hexadecimal values
As HSL values (CSS3)
As HWB values (CSS4)
```

**Comment by Swader** [comment]
From [Opensea metadata[(https://docs.opensea.io/docs/metadata-standards):

![image](https://user-images.githubusercontent.com/1430603/116418884-d3cf1480-a83c-11eb-87ea-9a20b8be99d6.png)

The goal is max compatibility unless absolutely necessary to break. What is the argument for breaking from this?

**Comment by vikiival** [comment]
> What is the argument for breaking from this?

[Kanaria NFT Metadata](https://ipfs.io/ipfs/bafkreigp3amcrr5urzntlyjpsvjccye4u7dvtyeatmlgzgecpy2kaczhka)

If this is typo on Kanaria side feel free to close

**Comment by Swader** [comment]
Good catch, that's an invalid background color, so will be ignored by UIs unless they add custom rendering for it.
